#!/bin/bash

# Install Moodle
/usr/bin/php /var/www/html/moodle/admin/cli/install.php \
    --wwwroot=$MOODLE_URL \
    --dataroot=$MOODLE_DATA \
    --dbtype=$DB_TYPE \
    --dbhost=$DB_HOST \
    --dbport=$DB_PORT \
    --dbname=$DB_NAME \
    --dbuser=$DB_USER \
    --dbpass=$DB_PASS \
    --fullname="Docker Moodle" \
    --adminpass=$ADMIN_PASS  \
    --shortname="Moodle" \
    --non-interactive \
    --agree-license \
    $(if [ $INIT_DB -eq 0 ]; then echo "--skip-database"; fi)

# Enable dev mode
#sed '/^\s*require_once/i\\// ENABLE DEVELOPER MODE' -i /var/www/html/moodle/config.php
#sed '/^\s*require_once/i\\$CFG->tool_generator_users_password = 'examplepassword';' -i /var/www/html/moodle/config.php
#sed '/^\s*require_once/i\\$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!' -i /var/www/html/moodle/config.php
#sed '/^\s*require_once/i\\$CFG->debugdisplay = 1;' -i /var/www/html/moodle/config.php


# add redis configuration
sed -i '/^\s*require_once/i\\$CFG->session_redis_host = '"'${REDIS_SERVER}';" /var/www/html/moodle/config.php
sed -i '/^\s*require_once/i\\$CFG->session_handler_class = '"'"'\\core\\session\\redis'"'"'\;' /var/www/html/moodle/config.php
sed -i '/^\s*require_once/i\\$CFG->session_redis_acquire_lock_timeout = 120;' /var/www/html/moodle/config.php
sed -i '/^\s*require_once/i\\$CFG->session_redis_lock_expire = 7200;' /var/www/html/moodle/config.php

#Enable Redis in PHP
echo "session.save_handler = redis" >> /etc/php7/conf.d/20_redis.ini
echo "session.save_path = \"tcp://${REDIS_SERVER}:6379\"" >> /etc/php7/conf.d/20_redis.ini

# Make apache owner of moodle files
chown -R apache:apache /var/moodledata
chown -R apache:apache /var/www/html

# set up crone
#echo "* * * * *    /usr/bin/php /var/www/html/moodle/admin/cli/cron.php >/dev/null" >> /var/spool/cron/root

# Generate test data
#/usr/bin/php /var/www/html/moodle/admin/tool/generator/maketestcourse.php \
#--shortname="TEST" \
#--fullname="AUTOGENERATED TEST COURSE" \
#--size="S" \
#--bypasscheck

# Run apache server
/usr/sbin/httpd -D FOREGROUND
