#!/bin/bash

# Install Moodle
/usr/bin/php /var/www/html/moodle/admin/cli/install.php \
    --wwwroot=$MOODLE_URL \
    --dataroot=$MOODLE_DATA \
    --dbtype=$DB_TYPE \
    --dbhost=$DB_HOST \
    --dbport=$DB_PORT \
    --dbname=$DB_NAME \
    --dbuser=$DB_USER \
    --dbpass=$DB_PASS \
    --fullname="Docker Moodle" \
    --adminpass=$ADMIN_PASS  \
    --shortname="Moodle" \
    --non-interactive \
    --agree-license \
    $(if [ $INIT_DB -eq 0 ]; then echo "--skip-database"; fi)

# Enable dev mode
echo "// ENABLE DEVELOPER MODE \n"  >> /var/www/html/moodle/config.php
echo "    $CFG->tool_generator_users_password = 'examplepassword'; \n \
    $CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!
    $CFG->debugdisplay = 1; \n" >> /var/www/html/moodle/config.php

# add redis configuration
echo "// REDIS CONFIGURATION \n" >> /var/www/html/moodle/config.php
echo "    $CFG->session_handler_class = '\core\session\redis'; \n \
    $CFG->session_redis_host = '127.0.0.1'; \n \
    $CFG->session_redis_acquire_lock_timeout = 120; \n \
    $CFG->session_redis_lock_expire = 7200; \n" >> /var/www/html/moodle/config.php

# Make apache owner of moodle files
chown -R apache:apache /var/moodledata
chown -R apache:apache /var/www/html

# set up crone
echo "* * * * *    /usr/bin/php /var/www/html/moodle/admin/cli/cron.php >/dev/null" >> /var/spool/cron/root

# Generate test data
/usr/bin/php /var/www/html/moodle/admin/tool/generator/maketestcourse.php \
--shortname="TEST" \
--fullname="AUTOGENERATED TEST COURSE" \
--size="S" \
--bypasscheck

# Run apache server
/usr/sbin/httpd -D FOREGROUND
